import math
import numpy as np
from typing import List, Tuple, Dict, Any
from datasets import *
from modelling_utils import Circle, is_point_in_circle, filter_point_set_modulo, generate_square_integer_points, square_to_quarter_circle, \
      min_max_distance, min_max_cosine, read_pickle, write_pickle

# The following code was partially generated by Claude AI https://claude.ai
def generate_track_middlepoints() -> List[Tuple[int,int]]:
    """
    Generates a list of all points in the middle of the track.
    :returns: List of tuples representing points (x,y) in the middle of the track
    """ 
    break_points = create_pathline()
    out = []
    # Process each segment between consecutive break points
    for i in range(len(break_points) - 1):
        x1, y1 = break_points[i]
        x2, y2 = break_points[i + 1]
        
        # Horizontal segment
        if y1 == y2:
            start_x, end_x = min(x1, x2), max(x1, x2)
            for x in range(start_x, end_x + 1):
                out.append((x, y1))
        
        # Vertical segment
        elif x1 == x2:
            start_y, end_y = min(y1, y2), max(y1, y2)
            for y in range(start_y, end_y + 1):
                out.append((x1, y))

    return out


def generate_all_points_on_track(extended_by: int = 0) -> List[Tuple[int,int]]:
    """
    Generates a list of all points on the the track.
    :param extended_by: by how much to increase or shrink the width of resulting lines; should be at 
    least -19 and at most 15. 
    :returns: List of tuples representing points (x,y) on the track
    """

    out_set = set()
    break_points = create_pathline()
    track_middle_points = generate_track_middlepoints()
    
    # Add points for the first middlepoint:
    for y_add in range(- 20 - extended_by, 21 + extended_by):
        out_set.add((-40, 230+y_add))

    # Add all other points, except for cornerpoints
    for i in range(1, len(track_middle_points), 1):
        x1 = track_middle_points[i-1][0]
        x2 = track_middle_points[i][0]
        y1 = track_middle_points[i-1][1]
        y2 = track_middle_points[i][1]

        # Horizontal segment
        if y1 == y2:
            for y_add in range(-20 - extended_by, 21 + extended_by):
               out_set.add((x2, y2+y_add))
        
        # Vertical segment
        elif x1 == x2:
            for x_add in range(-20 - extended_by, 21 + extended_by):
                out_set.add((x2+x_add, y2))
    
    # Add points around the corners of the track
    for i in range(1, len(break_points)-1, 1):
        points_in_square = generate_square_integer_points(break_points[i], 20 + extended_by)
        # Transform a square into a quarter circle with a correct orientation
        if break_points[i] in {(95,230), (210,350), (425,430), (430,185)}:
            point_in_quarter_circle = square_to_quarter_circle(points_in_square, 'upper_left')
        elif break_points[i] in {(95, 100), (55,350), (305,185)}:
            point_in_quarter_circle = square_to_quarter_circle(points_in_square, 'lower_right')
        elif break_points[i] in {(210,100), (425,300), (430,55)}:
            point_in_quarter_circle = square_to_quarter_circle(points_in_square, 'lower_left')
        elif break_points[i] in {(55,430), (305,300), (265,55)}:
            point_in_quarter_circle = square_to_quarter_circle(points_in_square, 'upper_right')

        # Delete points from track that are in the square but not in the quarter circle
        sq_not_qc = set(points_in_square) - set(point_in_quarter_circle)
        out_set = out_set - sq_not_qc

        # Add points in the quarter circle to the point on track
        for x,y in point_in_quarter_circle:
            out_set.add((x,y)) 
        

    # Make into a list and output   
    out = list(out_set)  

    return out
        
def generate_footprint_constraint_set(pos: Tuple[int,int], mode: str) -> List[Tuple[int,int]]:
    """
    Generates a set of points in which no tower can be placed given than there is already a tower placed at
    pos.
    :param pos: position in relation to which the set is computed
    :param mode: "nn" if towers of interest are non-SuperMonkeys; "ns" if one of the tower is a SuperMonkey
    and another one is not; "ss" is both towers are a super monkey. 
    :returns: List of tuples representing points (x,y) in which no tower can be built, given that
    a tower is built at pos
    """
    out = []
    if mode == "nn":
        zone_radius = 20 # footprint radius is 10 per monkey, and they cannot coincide
    elif mode == "ns":
        zone_radius = 25 # SuperMonkey has footprint 15, and non-SuperMonkey has footprint 10
    elif mode == "ss":
        zone_radius = 30 # SuperMonkey has footprint 15

    zone_circle = Circle((0,0,0), zone_radius, pos)
    min_x = pos[0] - zone_radius
    max_x = pos[0] + zone_radius
    min_y = pos[1] - zone_radius
    max_y = pos[1] + zone_radius

    for x in range(min_x, max_x+1):
        for y in range(min_y, max_y+1):
            # Check if it is in circle 
            if is_point_in_circle(zone_circle, x, y):
                out.append((x,y))
    
    return out


def generate_all_tower_placements(super_monkey: bool = False) -> List[Tuple[int, int]]: 
    """
    Generates a set of points in which towers can be placed.
    :returns: List of tuples representing points (x,y) in which towers can be places
    """
    if super_monkey:
        radius = 15
    else:
        radius = 10

    not_outside_set = set()
    for x in range(radius, 480 - radius):
        for y in range(radius, 480 - radius):
            not_outside_set.add((x,y))  
    
    too_close_to_track_set = set(generate_all_points_on_track(radius))

    out = list(not_outside_set - too_close_to_track_set)

    return out

   
def generate_coverage_dict() -> Dict[Tuple[int,int], int]:
    """
    Generates a dictionary containing the number of points in the middle of the track in the 
    range of a tower_type Tower, upgraded with upgrade_2 or not.
    :returns: A Dict of the form (x,y): # midpoint covered
    """
    tower_data = create_towers_dataframe()
    out = {}

    tower_placements = generate_all_tower_placements()
    midpoints = generate_track_middlepoints()

    options = [('Dart', 0), ('Dart', 1), ('Dart', 2), ('Dart', 3), ('Super Monkey', 0), ('Super Monkey', 2)]
    for tower, upgrade in options:
        if upgrade >= 2: # upgrade 2 increases range
            rad = tower_data.loc[tower, "upgrade_2_range"]
        else:
            rad = tower_data.loc[tower, "range"]

        for i in range(len(tower_placements)):
            var = tower_placements[i]
            circle = Circle(color=(0,0,0), radius=rad, pos=var)
            counter = 0
            for p in midpoints:
                if is_point_in_circle(circle, p[0], p[1]):
                    if upgrade == 1 or upgrade == 3: # upgrade 1 adds pierce, so it indirectly increases "coverage" (allows to strike more bloons)
                        counter += 1*1.75
                    else:
                        counter += 1
            
            if tower == 'Dart':
                out[(var, tower, upgrade)] = counter
            else:
                out[(var, tower, upgrade)] = (29/2)*counter # 29/2 is the proportion of Super Monkey to Dart attack speed 
    return out


def generate_distance_dict(scaling_bracket: Tuple[int,int] = (0, 1)) -> Dict[Tuple[int,int], int]: #TODO - properly define the scaling, resave after
    """
    Generates a dictionary containing the sum of the distances of the placement point of a tower to all the
    points in the middle of the track in the range of a tower_type Tower, upgraded with upgrade_2 or not.
    :param scaling_bracket: the result will be scaled into range (scaling_bracket[0], scaling_bracket[1])
    """
    tower_data = create_towers_dataframe()
    out = {}

    tower_placements = generate_all_tower_placements()
    midpoints = generate_track_middlepoints()

    options = [('Dart', 0), ('Dart', 1), ('Dart', 2), ('Dart', 3), ('Super Monkey', 0), ('Super Monkey', 2)]
    for tower, upgrade in options:
        if upgrade >= 2: # upgrade 2 increases range
            rad = tower_data.loc[tower, "upgrade_2_range"]
        else:
            rad = tower_data.loc[tower, "range"]

        for i in range(len(tower_placements)):
            var = tower_placements[i]
            circle = Circle(color=(0,0,0), radius=rad, pos=var)
            dist_sum = 0
            for p in midpoints:
                if is_point_in_circle(circle, p[0], p[1]):
                    dist_inv = (1/(math.dist(var, p))) 
                    if (upgrade == 1 or upgrade == 3): # upgrade 1 adds pierce, so it indirectly increases "coverage" (allows to strike more bloons)
                        dist_sum += 1.75*min_max_distance(scaling_bracket[0], scaling_bracket[1], dist_inv)
                    else:
                        dist_sum += min_max_distance(scaling_bracket[0], scaling_bracket[1], dist_inv)
                
            if tower == 'Dart':
                out[(var, tower, upgrade)] = dist_sum
            else: 
                out[(var, tower, upgrade)] = (29/2)*dist_sum # 29/2 is the proportion of Super Monkey to Dart attack speed 
            
        
    return out

def generate_midpoint_vector_map() -> Dict[Tuple[int,int], np.array]:
    """
    Generates a map from midpoints of the track to the vector made by the two
    breakpoints of the line that the midpoint is a part of.
    """
    break_points = create_pathline()
    out = {}
    # Process each segment between consecutive break points
    for i in range(len(break_points) - 1):
        pointls = []
        x1, y1 = break_points[i]
        x2, y2 = break_points[i + 1]
        
        vec = np.subtract((x1,y1), (x2, y2))

        # Horizontal segment
        if y1 == y2:
            start_x, end_x = min(x1, x2), max(x1, x2)
            for x in range(start_x, end_x + 1):
                pointls.append((x, y1))
        
        # Vertical segment
        elif x1 == x2:
            start_y, end_y = min(y1, y2), max(y1, y2)
            for y in range(start_y, end_y + 1):
                pointls.append((x1, y))

        for point in pointls:
            out[point] = vec

    return out

def compute_shooting_angle_cos(tower_pos: Tuple[int,int], midpoint: Tuple[int,int], midpoint_vector_map: Dict) -> float:
    """
    Computes the absolute value of a cosine of the angle between the vector joining the tower placement and 
    point in the middle of the track, and the vector joining two track breakpoints
    :returns: the absolute value of a cosine of the angle between the vector joining the tower placement and 
    point in the middle of the track, and the vector joining two track breakpoints
    """
    track_vec = midpoint_vector_map[midpoint]
    shooting_vec = np.subtract(midpoint, tower_pos)

    tv_norm = np.linalg.norm(track_vec)
    sv_norm = np.linalg.norm(shooting_vec)

    tv_unit = track_vec/tv_norm
    sv_unit = shooting_vec/sv_norm

    return(float(abs(np.dot(tv_unit, sv_unit))))

def generate_angle_coverage_dict(scaling_bracket: Tuple[int,int] = (0,1)) -> Dict[Tuple[int,int], int]:
    """
    Generates a dictionary containing the number of points in the middle of the track in the 
    range of a tower_type Tower, upgraded with upgrade_2 or not, which is weighted by the shooting angle.
    :returns: A Dict of the form (x,y): # midpoint covered
    """
    tower_data = create_towers_dataframe()
    out = {}

    tower_placements = generate_all_tower_placements()
    midpoints = generate_track_middlepoints()
    midpoint_vector_map = generate_midpoint_vector_map()
    cosine_threshold = (math.sqrt((30**2) - (13**2))/ 30) # cosine threshold for pierce bonus,  determined geometrically
    options = [('Dart', 0), ('Dart', 1), ('Dart', 2), ('Dart', 3), ('Super Monkey', 0), ('Super Monkey', 2)]
    for tower, upgrade in options:
        if upgrade >= 2: # upgrade 2 increases range
            rad = tower_data.loc[tower, "upgrade_2_range"]
        else:
            rad = tower_data.loc[tower, "range"]
        for i in range(len(tower_placements)):
            var = tower_placements[i]
            circle = Circle(color=(0,0,0), radius=rad, pos=var)
            ang_sum = 0
            for p in midpoints:
                if is_point_in_circle(circle, p[0], p[1]):
                    cosine = compute_shooting_angle_cos(var, p, midpoint_vector_map)
                    if (upgrade == 1 or upgrade == 3) and (cosine >= cosine_threshold): # upgrade 1 adds pierce, so it indirectly increases "coverage" (allows to strike more bloons)
                        ang_sum += 2*min_max_cosine(scaling_bracket[0], scaling_bracket[1], cosine)
                    else:
                        ang_sum += min_max_cosine(scaling_bracket[0], scaling_bracket[1], cosine)
            if tower == 'Dart':
                out[(var, tower, upgrade)] = ang_sum
            else: 
                out[(var, tower, upgrade)] = (29/2)*ang_sum # 29/2 is the proportion of Super Monkey to Dart attack speed 

    return out

def get_money_constraint_rhs(round_nr: int) -> int:
    """
    Determines the amount of money the player will have at the beginning of round 
    round_nr (best case).
    :param round_nr: Round number 
    :returns: Money available to the player at the beginning of round round_nr
    """
    total_money = 650 
    rounds_info = create_rounds_dataframe()

    if round_nr == 1:
        return total_money

    round_end_money = rounds_info.loc[1:round_nr-1, 'money_round_end'].sum()
    total_money += round_end_money 


    max_RBE = rounds_info.loc[1:round_nr-1,'RBE_Cash'].sum()
    total_money += max_RBE

    return total_money  

def generate_all_footprint_constraint_sets(mode: str, modulo: int = 1, adjust: bool = True) -> Dict[Tuple[int,int], List[Tuple[int,int]]]:
    """
    Generates all footprint constaint sets for the given mode.
    :param mode: "nn" if towers of interest are non-SuperMonkeys; "ns" if one of the tower is a SuperMonkey
    and another one is not; "ss" is both towers are a super monkey.
    :param modulo: number for the divisibility filter
    :param adjust: whether to substract points that are not in all possible tower positions from the 
    resulting set (True) or not (False)
    """
    out = {}

    if mode in ["ns", "ss"]:
        super_monkey = True
    else:
        super_monkey = False

    tower_placements = generate_all_tower_placements(super_monkey)
    tower_placements_mod = filter_point_set_modulo(tower_placements, modulo)

    # Set for quick inclusion check
    if adjust:
        tower_placement_set = set(tower_placements_mod)

    for i in range(len(tower_placements_mod)):
        var = tower_placements_mod[i]
        out[var] = []
        footprint_points = generate_footprint_constraint_set(var, mode)
        
        if adjust:
            # Disregard values than cannot be chosen for tower placement
            for point in footprint_points:
                if point in tower_placement_set:
                    out[var].append(point)

        else:
            out[var].append(point)
        

        if not adjust:
            # Filter for point divisibility
            out[var] = filter_point_set_modulo(out[var], modulo)

    return out


def generate_point_tower_set(modulo: int = 1) -> Dict[Tuple[int,int], List[Tuple[int,int,str,int]]]:
    """
    Generates a set of sets which for each point have a list of Towers that cover that point.
    """
    out = {}

    midpoints = generate_track_middlepoints()
    positions = generate_all_tower_placements()
    positions_s = generate_all_tower_placements(True)

    positions = filter_point_set_modulo(positions, modulo)
    positions_s = filter_point_set_modulo(positions_s, modulo)

    rang_01 = 100
    rang_23 = 125

    rang_s_0 = 140
    rang_s_2 = 240

    # Dart Tower
    for i in range(len(midpoints)):
        midp = midpoints[i]
        out[midp, 'Dart', 0] = []
        out[midp, 'Dart', 1] = []
        out[midp, 'Dart', 2] = []
        out[midp, 'Dart', 3] = []
        out[midp, 'Super Monkey', 0] = []
        out[midp, 'Super Monkey', 2] = []
        circ_01 = Circle((0,0,0), rang_01, midp)
        circ_23 = Circle((0,0,0), rang_23, midp)
        circ_s_0 = Circle((0,0,0), rang_s_0, midp)
        circ_s_2 = Circle((0,0,0), rang_s_2, midp)
        for pos in positions:
            if is_point_in_circle(circ_01, pos[0], pos[1]):
                out[midp, 'Dart', 0].append(pos)
                out[midp, 'Dart', 1].append(pos)
            if is_point_in_circle(circ_23, pos[0], pos[1]):
                out[midp, 'Dart', 2].append(pos)
                out[midp, 'Dart', 3].append(pos)
        for pos in positions_s:
            if is_point_in_circle(circ_s_0, pos[0], pos[1]):
                out[midp, 'Super Monkey', 0].append(pos)
            if is_point_in_circle(circ_s_2, pos[0], pos[1]):
                out[midp, 'Super Monkey', 2].append(pos)

    return(out)
            

def generate_vars_1(modulo: int) -> List[Tuple[int,int]]:
    """
    Generates a list of variables for Model1a.
    :param modulo: number for the divisibility filter
    """
    placements = read_pickle('PLACEMENTS')
    placements_mod = filter_point_set_modulo(placements, modulo)

    return placements_mod

def generate_sets_1a(modulo: int) -> Dict[str, List]:
    """
    Generates all sets needed for Model 1a.
    """
    TP = generate_vars_1(modulo)
    COV = read_pickle('COV')
    if modulo in [3,5,10]:
        FP = read_pickle(f'FP_{modulo}')
    else:
        FP = generate_all_footprint_constraint_sets("nn", modulo)

    return {'TP': TP, 'COV' : COV, 'FP' : FP}

def generate_sets_1b(modulo: int, scaling_bracket: Tuple[int,int] = (0,1)) -> Dict[str, List]:
    """
    Generates all sets needed for Model 1b.
    """
    TP = generate_vars_1(modulo) 

    if scaling_bracket == (0,1):
        DIST = read_pickle('DIST_0_1')
    elif scaling_bracket == (0.5,1):
        DIST = read_pickle('DIST_05_1')
    else:
        DIST = generate_distance_dict(scaling_bracket)

    if modulo in [3,5,10]:
        FP = read_pickle(f'FP_{modulo}')
    else:
        FP = generate_all_footprint_constraint_sets("nn", modulo)

    return {'TP': TP, 'DIST' : DIST, 'FP' : FP}

def generate_sets_1c(modulo: int, scaling_bracket: Tuple[int,int] = (0,1)) -> Dict[str, List]:
    """
    Generates all sets needed for Model 1c.
    """
    TP = generate_vars_1(modulo) 
    if scaling_bracket == (0,1):
        ANG_COV = read_pickle('ANG_0_1')
    elif scaling_bracket == (0.5,1):
        ANG_COV = read_pickle('ANG_05_1')
    else:
        ANG_COV = generate_angle_coverage_dict(scaling_bracket)

    if modulo in [3,5,10]:
        FP = read_pickle(f'FP_{modulo}')
    else:
        FP = generate_all_footprint_constraint_sets("nn", modulo)

    return {'TP': TP, 'FP' : FP, 'ANG_COV': ANG_COV}


def generate_vars_2(modulo: int):
    placements = generate_vars_1(modulo)
    rounds = [i+1 for i in range(50)]
    upgrades = [i for i in range(4)]

    return [rounds, placements, upgrades]

def generate_vars_3(modulo: int):
    placements = generate_vars_1(modulo)
    placements_s_raw = read_pickle('PLACEMENTS_S')
    placements_s = filter_point_set_modulo(placements_s_raw, modulo)

    rounds = [i+1 for i in range(50)]
    upgrades = [i for i in range(4)]
    upgrades_s = [0,2]

    return [[rounds, placements, upgrades], [rounds, placements_s, upgrades_s]]



def generate_tower_upgrade_costs() -> Dict[Tuple[str, int], int]:
    """
    Generates a dictionary with cumulative costs of building a tower with upgrades.
    :returns: a Dict with cumulative costs of building a tower with upgrades.
    """
    out = {}
    tower_data = create_towers_dataframe()
    upgrade_columns = ['cost', 'cumulative_cost_upgrade_1', 'cumulative_cost_upgrade_2', 'cumulative_cost_upgrade_12']
    for tower in tower_data.index:
        for upgrade in range(4):
            out[tower, upgrade] = tower_data.loc[tower, upgrade_columns[upgrade]]

    return out

def generate_money_constraints_rhs() -> Dict[int, int]:
    """
    Determines the amount of money the player will have at the beginning of round 
    round_nr (best case).
    :returns: Dict, of form {round_nr: money}
    """
    out = {}
    for i in range(50):
        out[i+1] = get_money_constraint_rhs(i+1)
    return out

def generate_sets_2a(modulo: int):
    variables = generate_vars_2(modulo)
    COV = read_pickle('COV')
    if modulo in [3,5,10]:
        FP = read_pickle(f'FP_{modulo}')
        MID_IN_RANGE = read_pickle(f'MIDP_TOWER_RNG_{modulo}')
    else:
        FP = generate_all_footprint_constraint_sets("nn", modulo)
        MID_IN_RANGE = generate_point_tower_set(modulo)
    COST = generate_tower_upgrade_costs()
    MONEY = generate_money_constraints_rhs()
    MIDP = generate_track_middlepoints()

    return {'VAR': variables, 'COV' : COV, 'FP' : FP, 'COST': COST, 'MONEY': MONEY, 'MID_IN_RANGE': MID_IN_RANGE, 'MIDP': MIDP}

def generate_sets_2b(modulo: int, scaling_bracket: Tuple[int,int] = (0,1)):
    variables = generate_vars_2(modulo)
    
    if scaling_bracket == (0,1):
        DIST = read_pickle('DIST_0_1')
    elif scaling_bracket == (0.5,1):
        DIST = read_pickle('DIST_05_1')
    else:
        DIST = generate_distance_dict(scaling_bracket)

    if modulo in [3,5,10]:
        FP = read_pickle(f'FP_{modulo}')
        MID_IN_RANGE = read_pickle(f'MIDP_TOWER_RNG_{modulo}')
    else:
        FP = generate_all_footprint_constraint_sets("nn", modulo)
        MID_IN_RANGE = generate_point_tower_set(modulo)
    COST = generate_tower_upgrade_costs()
    MONEY = generate_money_constraints_rhs()
    MIDP = generate_track_middlepoints()

    return {'VAR': variables, 'DIST' : DIST, 'FP' : FP, 'COST': COST, 'MONEY': MONEY, 'MID_IN_RANGE': MID_IN_RANGE, 'MIDP': MIDP}

def generate_sets_2c(modulo: int, scaling_bracket: Tuple[int,int] = (0,1)):
    variables = generate_vars_2(modulo)
    
    if scaling_bracket == (0,1):
        ANG_COV = read_pickle('ANG_0_1')
    elif scaling_bracket == (0.5,1):
        ANG_COV = read_pickle('ANG_05_1')
    else:
        ANG_COV = generate_angle_coverage_dict(scaling_bracket)

    if modulo in [3,5,10]:
        FP = read_pickle(f'FP_{modulo}')
        MID_IN_RANGE = read_pickle(f'MIDP_TOWER_RNG_{modulo}')
        
    else:
        FP = generate_all_footprint_constraint_sets("nn", modulo)
        MID_IN_RANGE = generate_point_tower_set(modulo)
       
    COST = generate_tower_upgrade_costs()
    MONEY = generate_money_constraints_rhs()
    MIDP = generate_track_middlepoints()
    

    return {'VAR': variables, 'ANG_COV' : ANG_COV, 'FP' : FP, 'COST': COST, 'MONEY': MONEY, 'MID_IN_RANGE': MID_IN_RANGE, 'MIDP': MIDP}

def generate_sets_3(modulo: int, scaling_bracket: Tuple[int,int] = (0,1)):
    variables = generate_vars_3(modulo)
    vars_d = variables[0]
    vars_s = variables[1]

    COV = read_pickle('COV')
    if scaling_bracket == (0,1):
        ANG_COV = read_pickle('ANG_0_1')
        DIST = read_pickle('DIST_0_1')
        
    elif scaling_bracket == (0.5,1):
        ANG_COV = read_pickle('ANG_05_1')
        DIST = read_pickle('DIST_05_1')
    else:
        ANG_COV = generate_angle_coverage_dict(scaling_bracket)
        DIST = generate_distance_dict(scaling_bracket)

    if modulo in [3,5,10]:
        FP = read_pickle(f'FP_{modulo}')
        FPNS = read_pickle(f'FPNS_{modulo}')
        FPSS = read_pickle(f'FPSS_{modulo}')
    else:
        FP = generate_all_footprint_constraint_sets("nn", modulo)
        FPNS = generate_all_footprint_constraint_sets("ns", modulo)
        FPSS = generate_all_footprint_constraint_sets("ss", modulo)
    COST = generate_tower_upgrade_costs()
    MONEY = generate_money_constraints_rhs()

    return {'VAR_D': vars_d,'VAR_S': vars_s, 'COV': COV, 'DIST': DIST, 'ANG_COV' : ANG_COV, 'FP' : FP, 'FPNS': FPNS, 'FPSS': FPSS, 'COST': COST, 'MONEY': MONEY}

def generate_and_save() -> None:
    """
    Generates the most time consuming sets of interest and saves them.
    """
    COV = generate_coverage_dict()
    write_pickle(COV, 'COV')
    DIST_0_1 = generate_distance_dict()
    write_pickle(DIST_0_1, 'DIST_0_1')
    DIST_05_1= generate_distance_dict((0.5, 1))
    write_pickle(DIST_05_1, 'DIST_05_1')
    ANG_0_1 = generate_angle_coverage_dict()
    write_pickle(ANG_0_1, 'ANG_0_1')
    ANG_05_1 = generate_angle_coverage_dict((0.5, 1))
    write_pickle(ANG_05_1, 'ANG_05_1')

    FP_10 = generate_all_footprint_constraint_sets("nn", 10)
    write_pickle(FP_10, 'FP_10')
    FP_5 = generate_all_footprint_constraint_sets("nn", 5)
    write_pickle(FP_5, 'FP_5')
    FP_3 = generate_all_footprint_constraint_sets("nn", 3)
    write_pickle(FP_3, 'FP_3')

    FPNS_10 = generate_all_footprint_constraint_sets("ns", 10)
    write_pickle(FPNS_10, 'FPNS_10')
    FPNS_5 = generate_all_footprint_constraint_sets("ns", 5)
    write_pickle(FPNS_5, 'FPNS_5')
    FPNS_3 = generate_all_footprint_constraint_sets("ns", 3)
    write_pickle(FPNS_3, 'FPNS_3')

    FPSS_10 = generate_all_footprint_constraint_sets("ss", 10)
    write_pickle(FPSS_10, 'FPSS_10')
    FPSS_5 = generate_all_footprint_constraint_sets("ss", 5)
    write_pickle(FPSS_5, 'FPSS_5')
    FPSS_3 = generate_all_footprint_constraint_sets("ss", 3)
    write_pickle(FPSS_3, 'FPSS_3')

    PLACEMENTS = generate_all_tower_placements()
    write_pickle(PLACEMENTS, 'PLACEMENTS')
    PLACEMENTS_S = generate_all_tower_placements(True)
    write_pickle(PLACEMENTS_S, 'PLACEMENTS_S')

    MIDPOINT_TOWER_RANGE_10 = generate_point_tower_set(10)
    write_pickle(MIDPOINT_TOWER_RANGE_10, 'MIDP_TOWER_RNG_10')

