from modelling_sets import generate_track_middlepoints, create_pathline, generate_footprint_constraint_set,generate_coverage_dict, generate_all_points_on_track, generate_all_tower_placements, generate_all_footprint_constraint_sets
from modelling_utils import generate_square_integer_points, square_to_quarter_circle
import matplotlib.pyplot as plt


# The following code was generated by Claude AI https://claude.ai
def plot_track(break_points, all_points):
    """
    Plot the track, highlighting the breakpoints.
    """
    plt.figure(figsize=(10, 6))
    
    # Extract x and y coordinates
    break_x, break_y = zip(*break_points)
    all_x, all_y = zip(*all_points)
    # Plot all integer points
    plt.plot(all_x, all_y, 'bx', markersize=4)
    
    # Plot break points
    plt.plot(break_x, break_y, 'ro', markersize=8)
    
    plt.grid(True)
    plt.legend()
    plt.xlabel('X')
    plt.ylabel('Y')
    plt.ylim(max(all_y) + 40, min(all_y))
    plt.axis('equal')
    plt.tight_layout()
    plt.show()


def plot_footprint_constraints(pos, zone_points):
    plt.figure(figsize=(10, 6))

    x, y = zip(*zone_points)
    plt.plot(pos[0], pos[1], 'rx', markersize=5)
    plt.plot(x,y, 'bo', markersize = 1)

    plt.legend()
    plt.xlabel('X')
    plt.ylabel('Y')
    plt.axis('equal')
    plt.tight_layout()
    plt.show()


def plot_points(points_list):
    plt.figure(figsize=(10, 6))

    for points in points_list:
        x, y = zip(*points)
        plt.scatter(x,y)

    plt.legend()
    plt.xlabel('X')
    plt.ylabel('Y')
    plt.ylim(max(y) + 40, min(x))
    plt.axis('equal')
    plt.tight_layout()
    plt.show()

def flatten(xss):
    return [x for xs in xss for x in xs]

   
bp = create_pathline()
tp = generate_all_points_on_track(extended_by=15)
plot_track(bp, tp)
