import math
import numpy as np
from typing import List, Tuple, Dict, Any
from datasets import *
from modelling_utils import Circle, is_point_in_circle, filter_point_set_module, generate_square_integer_points, square_to_right_triangle

# The following code was partially generated by Claude AI https://claude.ai
def generate_track_middlepoints() -> List[Tuple[int,int]]:
    """
    Generates a list of all points in the middle of the track.
    :returns: List of tuples representing points (x,y) in the middle of the track
    """ 
    break_points = create_pathline()
    out = []
    # Process each segment between consecutive break points
    for i in range(len(break_points) - 1):
        x1, y1 = break_points[i]
        x2, y2 = break_points[i + 1]
        
        # Horizontal segment
        if y1 == y2:
            start_x, end_x = min(x1, x2), max(x1, x2)
            for x in range(start_x, end_x + 1):
                out.append((x, y1))
        
        # Vertical segment
        elif x1 == x2:
            start_y, end_y = min(y1, y2), max(y1, y2)
            for y in range(start_y, end_y + 1):
                out.append((x1, y))

    return out


def generate_all_points_on_track(extended_by: int = 0) -> List[Tuple[int,int]]:
    """
    Generates a list of all points on the the track.
    :param extended_by: by how much to increase or shrink the width of resulting lines; should be at 
    most -19
    :returns: List of tuples representing points (x,y) on the track
    """

    out_set = set()
    break_points = create_pathline()
    track_middle_points = generate_track_middlepoints()
    
    # Add points for the first middlepoint:
    for y_add in range(- 20 - extended_by, 21 + extended_by):
        out_set.add((-40, 230+y_add))

    # Add all other points, except for cornerpoints
    for i in range(1, len(track_middle_points), 1):
        x1 = track_middle_points[i-1][0]
        x2 = track_middle_points[i][0]
        y1 = track_middle_points[i-1][1]
        y2 = track_middle_points[i][1]

        # Horizontal segment
        if y1 == y2:
            for y_add in range(-20 - extended_by, 21 + extended_by):
               out_set.add((x2, y2+y_add))
        
        # Vertical segment
        elif x1 == x2:
            for x_add in range(-20 - extended_by, 21 + extended_by):
                out_set.add((x2+x_add, y2))
    
    # Add points around the corners of the track
    for i in range(1, len(break_points)-1, 1):
        points_in_square = generate_square_integer_points(break_points[i], 20 + extended_by)
        for x,y in points_in_square:
            out_set.add((x,y))    

    # Make into a list and output   
    out = list(out_set)  

    return out
        
def generate_footprint_constraint_set(pos: Tuple[int,int], mode: str) -> List[Tuple[int,int]]:
    """
    Generates a set of points in which no tower can be placed given than there is already a tower placed at
    pos.
    :param pos: position in relation to which the set is computed
    :param mode: "nn" if towers of interest are non-SuperMonkeys; "ns" if one of the tower is a SuperMonkey
    and another one is not; "ss" is both towers are a super monkey. 
    :returns: List of tuples representing points (x,y) in which no tower can be built, given that
    a tower is built at pos
    """
    out = []
    if mode == "nn":
        zone_radius = 20 # footprint radius is 10 per monkey, and they cannot coincide
    elif mode == "ns":
        zone_radius = 25 # SuperMonkey has footprint 15, and non-SuperMonkey has footprint 10
    elif mode == "ss":
        zone_radius = 30 # SuperMonkey has footprint 15

    zone_circle = Circle((0,0,0), zone_radius, pos)
    min_x = pos[0] - zone_radius
    max_x = pos[0] + zone_radius
    min_y = pos[1] - zone_radius
    max_y = pos[1] + zone_radius

    for x in range(min_x, max_x+1):
        for y in range(min_y, max_y+1):
            # Check if it is in circle 
            if is_point_in_circle(zone_circle, x, y):
                out.append((x,y))
    
    return out


def generate_all_tower_placements(super_monkey: bool = False) -> List[Tuple[int, int]]: 
    """
    Generates a set of points in which towers can be placed.
    :returns: List of tuples representing points (x,y) in which towers can be places
    """
    if super_monkey:
        radius = 15
    else:
        radius = 10

    not_outside_set = set()
    for x in range(radius, 480 - radius):
        for y in range(radius, 480 - radius):
            not_outside_set.add((x,y))  
    
    too_close_to_track_set = set(generate_all_points_on_track(radius))

    out = list(not_outside_set - too_close_to_track_set)
    return out

   
def generate_coverage_dict(tower_type: str = 'Dart', upgrade_2: bool = False) -> Dict[Tuple[int,int], int]: # TODO - repurpose output to handle tower type and upgrade
    """
    Generates a dictionary containing the number of points in the middle of the track in the 
    range of a tower_type Tower, upgraded with upgrade_2 or not.
    :param tower_type: One of 'Dart', 'Tack', 'Bomb', 'Ice', 'SuperMonkey'
    :param upgrade_2: True if we want to consider the tower with upgrade 2 bought; False otherwise
    :returns: A Dict of the form (x,y): # midpoint covered
    """
    out = {}

    if not upgrade_2:
        rad = 100
    else:
        rad = 125
    tower_placements = generate_all_tower_placements()
    midpoints = generate_track_middlepoints()

    for i in range(len(tower_placements)):
        var = tower_placements[i]
        circle = Circle(color=(0,0,0), radius=rad, pos=var)
        counter = 0
        for p in midpoints:
            if is_point_in_circle(circle, p[0], p[1]):
                counter += 1
        out[var] = counter
    return out


def generate_distance_dict(alpha: float, tower_type: str = 'Dart', upgrade_1: bool = False, upgrade_2: bool = False) -> Dict[Tuple[int,int], int]: # TODO - repurpose output to handle tower type and upgrade
    """
    Generates a dictionary containing the average distance of the placement point of a tower to all
    the points in the middle of the track in the range of a tower_type Tower, upgraded with upgrade_2 or not.
    :param alpha: weight to give to count (so to the COVERAGE measure)
    :param tower_type: One of 'Dart', 'Tack', 'Bomb', 'Ice', 'SuperMonkey'
    :param upgrade_2: True if we want to consider the tower with upgrade 2 bought; False otherwise
    :returns: A Dict of the form (x,y): avegare_midpoint_distance
    """
    out = {}

    if not upgrade_2:
        rad = 100
    else:
        rad = 125
    tower_placements = generate_all_tower_placements()
    midpoints = generate_track_middlepoints()

    for i in range(len(tower_placements)):
        var = tower_placements[i]
        circle = Circle(color=(0,0,0), radius=rad, pos=var)
        counter = 0
        dist_sum = 1
        for p in midpoints:
            if is_point_in_circle(circle, p[0], p[1]):
                dist_sum += math.dist(var, p)
                counter += 1
        if counter <= 0:
            out[var] = float('Inf')
        else:
            out[var] = dist_sum/(counter*alpha)
    return out


# def generate_angle_coverage_dict(tower_type: str, upgrade_2: bool) -> Dict[Tuple[int,int], int]:
#     track = 
    

def get_money_constraint_rhs(round_nr: int) -> int:
    """
    Determines the amount of money the player will have at the beginning of round 
    round_nr (best case).
    :param round_nr: Round number 
    :returns: Money available to the player at the beginning of round round_nr
    """
    total_money = 650 
    rounds_info = create_rounds_dataframe()

    if round_nr == 1:
        return total_money

    round_end_money = rounds_info.loc[1:round_nr-1, 'money_round_end'].sum()
    total_money += round_end_money 


    max_RBE = rounds_info.loc[1:round_nr-1,'RBE_Cash'].sum()
    total_money += max_RBE

    return total_money  


def get_costs() -> Dict[str, int]:
    pass


def generate_all_footprint_constraint_sets(mode: str, modulo: int = 1, adjust: bool = True) -> Dict[Tuple[int,int], List[Tuple[int,int]]]:
    """
    Generates all footprint constaint sets for the given mode.
    :param mode: "nn" if towers of interest are non-SuperMonkeys; "ns" if one of the tower is a SuperMonkey
    and another one is not; "ss" is both towers are a super monkey.
    :param modulo: number for the divisibility filter
    :param adjust: whether to substract points that are not in all possible tower positions from the 
    resulting set (True) or not (False)
    """
    out = {}

    if mode == "ss":
        super_monkey = True
    else:
        super_monkey = False

    tower_placements = generate_all_tower_placements(super_monkey)
    tower_placements_mod = filter_point_set_module(tower_placements, modulo)

    # Set for quick inclusion check
    if adjust:
        tower_placement_set = set(tower_placements_mod)

    for i in range(len(tower_placements_mod)):
        var = tower_placements_mod[i]
        out[var] = []
        footprint_points = generate_footprint_constraint_set(var, mode)
        
        if adjust:
            # Disregard values than cannot be chosen for tower placement
            for point in footprint_points:
                if point in tower_placement_set:
                    out[var].append(point)

        else:
            out[var].append(point)
        

        if not adjust:
            # Filter for point divisibility
            out[var] = filter_point_set_module(out[var], modulo)

    return out


def generate_vars_1a(modulo: int) -> List[Tuple[int,int]]:
    """
    Generates a list of variables for Model1a.
    :param modulo: number for the divisibility filter
    """
    placements = generate_all_tower_placements(False)
    placements_mod = filter_point_set_module(placements, modulo)

    return placements_mod

def generate_sets_1a(modulo: int) -> Dict[str, List]:
    """
    Generates all sets needed for Model 1a.
    """
    TP = generate_vars_1a(modulo)
    COV = generate_coverage_dict()
    FP = generate_all_footprint_constraint_sets("nn", modulo)

    return {'TP': TP, 'COV' : COV, 'FP' : FP}

def generate_sets_1b(modulo: int, alpha: float) -> Dict[str, List]:
    """
    Generates all sets needed for Model 1b.
    """
    TP = generate_vars_1a(modulo) # Use the same set of vars as 1a
    DIST = generate_distance_dict(alpha)
    FP = generate_all_footprint_constraint_sets("nn", modulo)

    return {'TP': TP, 'DIST' : DIST, 'FP' : FP}

def generate_var_label_sets(modulo: int) -> Tuple[Tuple]:
    """
    
    """
    placements_nonsuper = generate_all_tower_placements(False)
    placements_super = generate_all_tower_placements(True)

    placements_nonsuper_mod = filter_point_set_module(placements_nonsuper, modulo)
    placements_super_mod = filter_point_set_module(placements_super, modulo)

    monkey_types_nonsuper = ['Dart', 'Tack', 'Bomb', 'Ice']
    monkey_types_super = 'SuperMonkey'

    upgrade_vals_nonsuper = (0,1,2)
    upgrade_vals_super = (0,1)

    return ((placements_nonsuper_mod, monkey_types_nonsuper, upgrade_vals_nonsuper), (placements_super_mod, monkey_types_super, upgrade_vals_super))


