from modelling_sets import generate_track_middlepoints, create_pathline, generate_footprint_constraint_set,generate_coverage_dict, generate_all_points_on_track, generate_all_tower_placements, generate_all_footprint_constraint_sets
import matplotlib.pyplot as plt


# The following code was generated by Claude AI https://claude.ai
def plot_track(break_points, all_points):
    """
    Plot the track, highlighting the breakpoints.
    """
    plt.figure(figsize=(10, 6))
    
    # Extract x and y coordinates
    break_x, break_y = zip(*break_points)
    all_x, all_y = zip(*all_points)
    # Plot all integer points
    plt.plot(all_x, all_y, 'bx', markersize=4)
    
    # Plot break points
    plt.plot(break_x, break_y, 'ro', markersize=8)
    
    plt.grid(True)
    plt.legend()
    plt.xlabel('X')
    plt.ylabel('Y')
    plt.ylim(max(all_y) + 40, min(all_y))
    plt.axis('equal')
    plt.tight_layout()
    plt.show()


def plot_footprint_constraints(pos, zone_points):
    plt.figure(figsize=(10, 6))

    x, y = zip(*zone_points)
    plt.plot(pos[0], pos[1], 'rx', markersize=5)
    plt.plot(x,y, 'bo', markersize = 1)

    plt.legend()
    plt.xlabel('X')
    plt.ylabel('Y')
    plt.axis('equal')
    plt.tight_layout()
    plt.show()


def plot_points(points):
    plt.figure(figsize=(10, 6))

    x, y = zip(*points)
    plt.plot(x,y, 'bo', markersize = 1)

    plt.legend()
    plt.xlabel('X')
    plt.ylabel('Y')
    plt.ylim(max(y) + 40, min(x))
    plt.axis('equal')
    plt.tight_layout()
    plt.show()

def flatten(xss):
    return [x for xs in xss for x in xs]

track = generate_all_points_on_track()
p = [(150, 150), (170, 190), (340, 370), (170, 150), (130, 190), (340, 110), (360, 380), (360, 340), (130, 150), (380, 350), (380, 220), (370, 240), (360, 130), (390, 240), (380, 140), (360, 220), (150, 170), (380, 100), (150, 390), (270, 230), (350, 240), (170, 170), (110, 390), (170, 390), (340, 130), (340, 350), (360, 360), (130, 170), (380, 370), (130, 390), (370, 260), (390, 260), (150, 190), (360, 110), (270, 250), (380, 120), (350, 260)]

plot_track(p, track)
