import math
import numpy as np
import matplotlib.pyplot as plt
import pickle
from typing import List, Tuple, Dict


from utils import *

def is_point_modulo(point: Tuple[int,int], modulo: int) -> bool:
    """
    Checks if both coordinates of a point are divisible by a number.
    :param point: An (x,y) tuple
    :param modulo: number for the divisibility check
    :returns: True if both coordinates are divisible by modulo; False otherwise
    """
    x, y = point
    if (x%modulo == 0 and y%modulo == 0):
        return True
    return False

def filter_point_set_modulo(points: List[Tuple[int,int]], modulo: int) -> List[Tuple[int,int]]:
    """
    Filters a list of points, checking if both coordinates of a point are divisible by a number. Approximately
    1/(modulo^2) points will be kept, assuming a uniformly random distribution.
    :param points: A List of points (x,y) 
    :param modulo: number for the divisibility check
    :returns: A List of points (x,y) such that x, y are both divisible by modulo
    """
    out = []
    for point in points:
        if is_point_modulo(point, modulo):
            out.append(point)
    return out

# The following code was mostly generated by Claude AI https://claude.ai
def generate_square_integer_points(center: Tuple[int, int], width: int, modulo: int = 1) -> List[Tuple[int,int]]:
    """
    Generates all integer points that lie within a square.
    :param center: coordinates of the square's center, (x,y) tuple
    :param width: shortest distance from center to edge (half the side length).
    :param modulo: if both point coordinates are divisible by modulo, it will be kept; approximately
    1/(modulo^2) points will be kept
    """
    center_x, center_y = center
    
    # Calculate the square boundaries
    min_x = center_x - width
    max_x = center_x + width
    min_y = center_y - width
    max_y = center_y + width
    
    # Generate all integer points within the square
    points = []
    for x in range(min_x, max_x + 1):
        for y in range(min_y, max_y + 1):
            # Filter for divisibility
            if is_point_modulo((x,y), modulo):
                points.append((x, y))
    
    return points


# The following code was mostly generated by Claude AI https://claude.ai
def square_to_right_triangle(square_points: List[Tuple[int,int]], orientation: str) -> List[Tuple[int,int]]:
    """
    Convert a set of integer points forming a square to a set forming a right triangle.
    The triangle will be half of the square with the square's diagonal as the hypotenuse.
    :param square_points : list of (x, y) integer coordinates that form a square.
    :param orientation: Which half of the square to return as a triangle. Can be 'lower_left',
    'upper_left', 'lower_right', or 'upper_right'.
    :returns: List of (x, y) integer points that form a right triangle.
    """

    # Validate orientation parameter
    valid_orientations = ['lower_left', 'upper_left', 'lower_right', 'upper_right']
    if orientation not in valid_orientations:
        raise ValueError(f"Orientation must be one of {valid_orientations}")
    
    # Find the bounds of the square
    x_coords = [p[0] for p in square_points]
    y_coords = [p[1] for p in square_points]
    
    min_x, max_x = min(x_coords), max(x_coords)
    min_y, max_y = min(y_coords), max(y_coords)
    
    # Select points based on orientation
    triangle_points = []
    
    for x, y in square_points:
        if orientation == 'lower_left':
            # Points below the diagonal from bottom-left to top-right
            if x + y <= max_x + min_y:
                triangle_points.append((x, y))
        elif orientation == 'upper_left':
            # Points above the diagonal from bottom-left to top-right
            if x + y >= max_x + min_y:
                triangle_points.append((x, y))
        elif orientation == 'lower_right':
            # Points below the diagonal from top-left to bottom-right
            if y - x <= min_y - min_x:
                triangle_points.append((x, y))
        elif orientation == 'upper_right':
            # Points above the diagonal from top-left to bottom-right
            if y - x >= min_y - min_x:
                triangle_points.append((x, y))
    
    return triangle_points


def square_to_quarter_circle(square_points: List[Tuple[int,int]], orientation: str, modulo: int = 1) -> List[Tuple[int,int]]:
    """
    Convert a set of integer points forming a square to a set forming a quarter_circle.
    The quarter circle will be inscribed into a square, with the square's sides equal to
    the radius of the circle.
    :param square_points : list of (x, y) integer coordinates that form a square.
    :param square_center: center of the square
    :param orientation: Which half of the square to return as a quarter circle. Can be 'lower_left',
    'upper_left', 'lower_right', or 'upper_right'.
    :returns: List of (x, y) integer points that form a quarter circle.
    """
    out = []
    
    # Validate orientation parameter
    valid_orientations = ['lower_left', 'upper_left', 'lower_right', 'upper_right']
    if orientation not in valid_orientations:
        raise ValueError(f"Orientation must be one of {valid_orientations}")
    
    # Find the bounds of the square
    x_coords = [p[0] for p in square_points]
    y_coords = [p[1] for p in square_points]

    min_x, max_x = min(x_coords), max(x_coords)
    min_y, max_y = min(y_coords), max(y_coords)
    side_len = max_x - min_x 
    rad = side_len + 0.1 # adding 0.1 to include the cornerpoints of the square
    if orientation == 'lower_left':
        circle = Circle((0,0,0), rad, [min_x, max_y])
        
    elif orientation == 'upper_left':
        circle = Circle((0,0,0), rad, [min_x, min_y])

    elif orientation == 'lower_right':
        circle = Circle((0,0,0), rad, [max_x, max_y])
    
    elif orientation == 'upper_right':
        circle = Circle((0,0,0), rad, [max_x, min_y])

    for p in square_points:
        if is_point_in_circle(circle, p[0], p[1]):
            # Filter for divisibility
            if is_point_modulo(p, modulo):
                out.append(p)

    return out


def compute_distance_from_centre(pos: Tuple[int,int]) -> float:
    """
    Computes the distance from the centre to the point with position pos.
    :param pos: position of the point (x,y)
    :returns: Eucledean distance to point (239.5, 239.5), which is the centre of the map
    """
    return math.dist(pos, (239.5,239.5))


def sort_positions_by_middle_dist(positions: List[Tuple[int,int]]) -> List[Tuple[int,int]]:
    """
    Sorts a list of positions by their distance to the middle point of the map (ascending).
    :param positions: A list of points (x,y)
    :returns: A list of points (x,y), sorted by their distance 
    """
    pos_dist = {}
    for pos in positions:
        pos_dist[pos] = compute_distance_from_centre(pos)
    return sorted(pos_dist, key = pos_dist.get)

def get_empty_tower_queue() -> Dict[int, List[None]]:
    """
    Makes an empty tower queue.
    :returns: A tower queue of the form {1:[], 2:[], ..., 50:[]} 
    """
    out = {}
    for i in range(50):
        out[i+1] = []
    return out     

# Adopted from sklearn's implementation
def min_max_scaling(mn: float, mx: float, vals: List[float]) -> List[float]:
    """
    Applies min-max scaling to a list of values
    """
    val_min = min(vals)
    val_max = max(vals)
    out = []
    for val in vals:
        std = (val - val_min) / (val_max - val_min)
        out.append(std * (mx - mn) + mn)
    return out


def min_max_cosine(mn: float, mx: float, val: float) -> float:
    """
    Applies min-max scaling to a cosine function.
    """
    return val*(mx - mn) + mn

def min_max_distance(mn: float, mx: float, val: float) -> float:
    min_dist_inv = 1/240 # inverse of range of upgraded Super Monkey Tower
    max_dist_inv = 1/30  # inverse of smallest possible distace from Tower (radius 10) to the middle of the track (width 20)

    std = (val - min_dist_inv) / (max_dist_inv - min_dist_inv)
    return std*(mx - mn) + mn

def write_pickle(obj, savename, experiments: bool = False):
    if not experiments:
        filename = f'simulation/data/{savename}.pkl'
    else:
        filename = f'simulation/experiments/{savename}.pkl'
    with open(filename, 'wb') as f:
        pickle.dump(obj, f)

def read_pickle(filename, experiments: bool = False):
    if not experiments:
        path = f'simulation/data/{filename}.pkl'
    else:
        path = f'simulation/experiments/{filename}.pkl'
    with open(path, 'rb') as f:
        return pickle.load(f)
